### ISSUE TITLE
Cite a key paper claiming there is a 'reproducibility crisis' in science.

### ISSUE THREAD

**Issue by tmcphillips** [whole-tale/reproducibility-components#11]
As a reference for "the perceived 'reproducibility crisis in science'" the introduction currently cites *[Is science really facing a reproducibility crisis, and do we need it to? (Fanelli, 2018)](https://www.pnas.org/content/115/11/2628)* which states that:

> The new “science is in crisis” narrative is not only empirically unsupported, but also quite obviously counterproductive.

We of course should also cite a paper making the case the crisis is real and the discourse around it productive.

**Comment by tmcphillips** [comment]
@victoriastodden Do you have a good reference to recommend here, ideally a peer-reviewed paper? (There is always the *[1,500 scientists lift the lid on reproducibility](https://www.nature.com/news/1-500-scientists-lift-the-lid-on-reproducibility-1.19970)* survey results, but that's a Nature "News Feature"). Thank you.

**Comment by victoriastodden** [comment]
Here is one I like to cite https://ieeexplore.ieee.org/document/4720218

**Comment by tmcphillips** [comment]
This is perfect, thank you!

**Comment by tmcphillips** [comment]
I cited both of these papers.
