### ISSUE TITLE
Credit PRIMAD model with idea of dimensions of reproducibility

### ISSUE THREAD

**Issue by tmcphillips** [whole-tale/reproducibility-components#12]
According to the [Reproducibility of Data-Oriented Experiments in e-Science (Dagstuhl Seminar 16041)](http://drops.dagstuhl.de/opus/volltexte/2016/5817/) report, the PRIMAD model addresses the following question:

> When trying to reproduce a study, what are the things that are kept the same (e.g., the overall method or algorithm) and what is changed?

The implication is that each variable can be changed independently, such that there is a space of possible reproducible studies. Each PRIMAD variable is a different dimension (or a basis vector, not necessarily orthogonal to the others) of that space.  This is not (necessarily) the same reproducibility space as that hypothesized in the paper, but the idea is similar--and perhaps the two spaces _are_ the same, just with different basis vectors.

We should make this connection explicitly in the paper.  @ludaesch Is there a reference other than the Dagstuhl report above we can cite, and do you want to draft a paragraph to this effect?  Thank you.

**Comment by ludaesch** [comment]
I suggest we cite the chapter within the Dagstuhl report (I have the corresponding bibtex ready I think). Will also provide a paragraph shortly.
