### ISSUE TITLE
Find alternative to the word 'orthogonal'

### ISSUE THREAD

**Issue by tmcphillips** [whole-tale/reproducibility-components#4]
I really need help with this one:

> R2.18 I disagree with the assertion that transparency and re-executability are orthogonal.

This is an interesting objection.  I agree that we have neither proved nor demonstrated this.  And a disagreement by a reviewer is a serious thing.  Other readers who disagree with this statement are likely to put the paper down and never finish reading it later.

However, I find the reviewer's next statement, which continues this thought, very confusing. It seems to *endorse* the idea that transparency and re-executability are orthogonal:

> R2.19 They can be (e.g. detailed provenance vs. black-box execution), but I would argue that they are more likely aligned (a script that specifies inputs/outputs and intermediate steps can aid both).

If a particular research artifact "can be" a contribution just to *transparency*, or just to *re-executability* (as the reviewer affirms here), then in my mind the properties of transparency and re-executability are in principle *orthogonal*.  The observation that a typical research artifact contributes more or less to both (i.e. represents a linear combination of transparency and re-executability) does not contradict this. 

How can this be phrased more clearly? What word can we use instead of "orthogonal"?

**Comment by tmcphillips** [comment]
I was thinking about expanding this idea further in a footnote that explains the idea in terms of vector spaces where vectors generally are linear combinations of more than one basis vector, but some vectors are aligned with just one basis vector.  Analogously, most scripts in a study contribute to both transparency and re-executability (as the reviewer says), but one can imagine cases where an artifact in a study contributes only to one or the other (e.g. a call to a remote web service that operates as a black box is re-executable but might not be transparent).

@snunezcr Does this make any sense, and would you consider helping me with the wording?  Your grasp of mathematics far exceeds mine.

**Comment by snunezcr** [comment]
> I was thinking about expanding this idea further in a footnote that explains the idea in terms of vector spaces where vectors generally are linear combinations of more than one basis vector, but some vectors are aligned with just one basis vector.

We may rather operate on a more general notion of an affine space, one in which it is possible to have a vector space spanned by a small set of vectors whose inner product is not orthogonal (e.g. generating a honeycomb lattice with a horizontal, a 120deg vector and a 240 deg vector; their Euclidean norm is expressed in terms of positive and negative sine/cosine functions -so no orthogonality-, but you can locate every point in the space in this manner). 

> Analogously, most scripts in a study contribute to both transparency and re-executability (as the reviewer says), but one can imagine cases where an artifact in a study contributes only to one or the other (e.g. a call to a remote web service that operates as a black box is re-executable but might not be transparent).

Maybe we can say something more general (and possibly more useful as well): that while transparency and re-executability may be taken as separate qualities enforced by scripts, the expectation that these must intersect always in a given study is by no means justified.

> @snunezcr Does this make any sense, and would you consider helping me with the wording? Your grasp of mathematics far exceeds mine.

Glad to. I'll check this when I get to this part and try to write it as best as possible.

**Comment by tmcphillips** [comment]
I now think the confusion arises from the multiple meanings of the word *orthogonal*.  In addition to the geometric/algebraic sense which implies linear independence (what I had in mind), there is a statistical sense indicating *statistical* independence, which is an entirely different thing.

**Comment by tmcphillips** [comment]
Annotated the word *orthgonal* with this footnote: 
> In the geometric (not the statistical) sense of the word. Most scripts associated with a
study indeed contribute to both transparency and repeatability. But not infrequently
an artifact in a study contributes only to one or the other of these dimensions. For
example, an invocation of a remote web service that effectively operates as a black
box can be considered repeatable but not transparent.
